# Generated by Django 2.2.13 on 2020-06-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhibliMovies',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=125)),
                ('producer', models.CharField(max_length=125)),
                ('release_date', models.CharField(max_length=125)),
                ('rt_score', models.IntegerField(max_length=125)),
            ],
        ),
    ]
