# Generated by Django 2.2.14 on 2020-07-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghibli', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GhibliMovies',
        ),
    ]
